### ISSUE TITLE
script.js: getWeatherInfo is not defined

### ISSUE THREAD

**Issue by B-Dionysus** [jalbert12485/covid-tracking#10]
When user removes item from search history:

script.js:62 Uncaught ReferenceError: getWeatherInfo is not defined

**Comment by jalbert12485** [comment]
I've resolved this issue by removing references to getWeatherInfo, which was copied from previous work and not used in this project.   This was left in onclick references.  I also updated the code to properly save the user input to properly save to the local storage.
